### ISSUE TITLE
How to start the planning process?

### ISSUE THREAD

**Issue by ArlenCHEN** [HKUST-Aerial-Robotics/pointcloudTraj#1]
Hi,

Firstly, thanks for sharing the code!

I run the command: `roslaunch pointcloudTraj clean_demo.launch` , then the rviz shows the red little drone and the map with obstacles. But I am wondering how to start the planning process in the clean_demo?

Thanks a lot!

Best,
Zheng

**Comment by USTfgaoaa** [comment]
@ArlenCHEN 

Sorry about that, using that launch the mission should start automatically.
I will check it soon.

**Comment by USTfgaoaa** [comment]
@ArlenCHEN 

It's fixed. Just because of a spelling error of a ros-topic name in the launch file.
Try it again.

Best,
Fei

**Comment by ArlenCHEN** [comment]
Hi Fei,

Yes, now the clean_demo.launch works! Thanks so much!
Best,
Zheng

**Comment by infinity0323** [comment]
> @ArlenCHEN
> 
> It's fixed. Just because of a spelling error of a ros-topic name in the launch file.
> Try it again.
> 
> Best,
> Fei

Hi! I still have the same problem. The planning didn't start automatically. It has some green lines on the map.
I use Ubuntu18.04 and ROS Melodic to test the code.Will it have any effect?

Best,
Cui
